WIP  #13  juniors guide
fidals/fidals.com pull request #14
Opened 2018-02-23 16:40 UTC by duker33

WIP because article about home vs office required

2018-02-25 14:47 UTC, ArtemijRodionov requested changes

2018-02-25 14:47 UTC, ArtemijRodionov commented on src/dev/learn_to_work.md
> +- Все вокруг традиционно рекомендуют книгу Programming in python3
Никогда не слышал об этой книге :)

Приложу ссылки нескольких вариантов, отсортированных по  краткости:
https://learnxinyminutes.com/docs/ru-ru/python3-ru/ - самый быстрый способ стать питонистом
https://python.swaroopch.com/ - по моему мнению, лучшая книга для начала. есть русский перевод
http://www.diveintopython3.net/ - вариант для продолжения

2018-02-25 14:47 UTC, ArtemijRodionov commented on src/dev/learn_to_work.md
> +что такое сервер (софтовый) что такое Linux и какие там команды.
>сервер (софтовый)

backend?

2018-02-25 14:47 UTC, ArtemijRodionov commented on src/dev/learn_to_work.md
> +что такое сервер (софтовый) что такое Linux и какие там команды.
>что такое Linux и какие там команды.

как работать с Linux

2018-02-25 14:47 UTC, ArtemijRodionov commented on src/dev/learn_to_work.md
> +1. Питон.
Было бы здорово указать к этим пунктам ссылки на их "якоря" оглавлений

2018-02-25 14:47 UTC, ArtemijRodionov commented on src/dev/learn_to_work.md
> +### Баланс работа/обучение
Я бы поместил это в конец, как хорошее напутствие к действиям :)

2018-02-25 14:47 UTC, artemiy312 commented on src/dev/learn_to_work.md
> +- [Курс на geekbrains](https://geekbrains.ru/professions/python_developer) -
В сети очень много бесплатных и хороших ресурсов, где можно изучить питон с помощью mooc. Давай лучше добавим их: https://stepik.org/ , https://www.edx.org/ , https://www.coursera.org/

2018-02-25 14:47 UTC, artemiy312 commented on src/dev/learn_to_work.md
> +в mysql/postgres.
>`в mysql/postgres.` 

для первого раза будет намного проще использовать `sqlite`

2018-02-25 14:47 UTC, artemiy312 commented on src/dev/learn_to_work.md
> +1. linux + linux bash
https://github.com/Idnan/bash-guide - хороший материал про баш

2018-02-25 14:47 UTC, artemiy312 commented on src/dev/learn_to_work.md
> +1. http
https://developer.mozilla.org/en-US/docs/Web/HTTP гайд и референс по http

2018-02-25 14:47 UTC, artemiy312 commented on src/dev/learn_to_work.md
> +1. docker
https://docker-curriculum.com/
https://docs.docker.com/get-started/

2018-02-25 14:47 UTC, artemiy312 commented on src/dev/learn_to_work.md
> +рекомендую книгу МакКонела "Совершенный код" (McConnell "CodeComplete").
Мне кажется эта книга выходит за рамки нашего junior гайда :)

2018-02-26 07:44 UTC, duker33 commented on src/dev/learn_to_work.md
> +что такое сервер (софтовый) что такое Linux и какие там команды.
@artemiy312 , "бэкэнд" - это слишком общее понятие, я как раз пытаюсь вкратце объяснить из чего он состоит. Из сервера, который стоит на Линуксе, в котором нужно копаться башем.

> как работать с Linux

да, это будет куда лучше.

Итого предлагаю так:
```
1. Веб-сервисы. Как работает http, что такое application server, как работать с Linux.
```

2018-02-26 07:45 UTC, duker33 commented on src/dev/learn_to_work.md
> +1. Питон.
эмм, не шарю как это делается в Маркдауне, но попробую

TODO

2018-02-26 07:51 UTC, duker33 commented on src/dev/learn_to_work.md
> +### Баланс работа/обучение
@artemiy312 , да, это немного отвлечённый пункт и похожий на напутствие. Расположен не идеально. Но есть пару моментов по структуре:
- это подпункт раздела "для новичков". Аудитория статьи у нас делится на две части: js-мидлы и полные новички. Мидлам любого языка не надо читать всё это хозяйство "что такое бэкэнд" и "как надо ботать". Поэтому я во вступлении говорю "пропускайте раздел для новичков"
- весь "для новичков" в начале потому, что я сначала даю общий обзор тем, а потом раскрываю каждую. Мидлам общий обзор не нужен

Вот и получается, что отвлечённый пункт в начале. Пока не шарю как это пофиксить

2018-02-26 08:04 UTC, duker33 commented on src/dev/learn_to_work.md
> +в mysql/postgres.
@artemiy312 , в каком-нить CodeAcademy мб написано mysql для маркетинга и это может ввести в замешательство. На нулевом левеле знакомства с БД неочевидно, что у sqlite и mysql почти один и тот же синтаксис.

Предлагаю так:
```
... SELECT/INSERT запросы в sqlite (или mysql/postgres).
```

TODO

2018-02-26 08:06 UTC, duker33 commented on src/dev/learn_to_work.md
> +1. linux + linux bash
@artemiy312 , оке, добавлю и твой и ещё этот:
http://guide.bash.academy/

TODO

2018-02-26 08:07 UTC, duker33 commented on src/dev/learn_to_work.md
> +1. http
TODO

2018-02-26 08:08 UTC, duker33 commented on src/dev/learn_to_work.md
> +- [Курс на geekbrains](https://geekbrains.ru/professions/python_developer) -
TODO

2018-02-26 08:09 UTC, duker33 commented on src/dev/learn_to_work.md
> +1. docker
TODO

2018-02-26 08:10 UTC, duker33 commented on src/dev/learn_to_work.md
> +рекомендую книгу МакКонела "Совершенный код" (McConnell "CodeComplete").
@artemiy312 , ну видишь, это для мидлов, о чём я писал чуть выше.
Уже думаю что с этим делать. Мб просто выпустим две отдельные статьи

TODO

2018-02-26 08:54 UTC, duker33 commented
@artemiy312 , го таки разделим материал на две отдельные статьи.
"Для мидлов" и "Для новичков". Перелинкуем их в начале как следует

2018-02-26 09:48 UTC, duker33 commented
@artemiy312 , разделил, сделал все фиксы, кроме перелинковки оглавления.
Это чуть позже, а пока можно ревьювить

2018-02-26 13:01 UTC, ArtemijRodionov requested changes

2018-02-26 13:01 UTC, artemiy312 commented on src/learn/junior.md
> +- [http://pythontutor.ru/](http://pythontutor.ru/) - основы и упражнения по синтаксису.
Я [оставлял](https://github.com/fidals/fidals.com/pull/14#discussion_r170315183) ссылки на бесплатные книжки и статьи в прошлом ревью. Они крайне годные. Особенно первый линк. Продублирую:
>Приложу ссылки нескольких вариантов, отсортированных по краткости:
https://learnxinyminutes.com/docs/ru-ru/python3-ru/ - самый быстрый способ стать питонистом
https://python.swaroopch.com/ - по моему мнению, лучшая книга для начала. есть русский перевод
http://www.diveintopython3.net/ - вариант для продолжения

2018-02-26 13:01 UTC, artemiy312 commented on src/learn/middle.md
> +- Традиционно рекомендуют книгу Programming in python3
Ссылки про питон из `src/learn/junior.md` тут еще более актуальны

2018-02-26 13:41 UTC, duker33 commented on src/learn/middle.md
> +- Традиционно рекомендуют книгу Programming in python3
TODO

2018-02-26 13:42 UTC, duker33 commented on src/learn/junior.md
> +- [http://pythontutor.ru/](http://pythontutor.ru/) - основы и упражнения по синтаксису.
@artemiy312 , уупс, простите. Заменю на твои

TODO

2018-02-26 14:24 UTC, ArtemijRodionov approved these changes

2018-02-26 14:40 UTC, merged