#article  Juniour on remote
fidals/fidals.com pull request #15
Opened 2018-02-24 14:54 UTC by duker33

2018-02-25 19:55 UTC, ArtemijRodionov requested changes

2018-02-25 19:55 UTC, ArtemijRodionov commented on src/dev/junior_on_remote.md
> +Второй пункт выглядит ожидаемо, а вот первый - нет. Как и их разделение.
Не совсем понимаю, почему живое общение в офисе не ожидаемо. Когда люди находятся в коллективе, они всегда говорят о чем-то.

2018-02-25 19:55 UTC, ArtemijRodionov commented on src/dev/junior_on_remote.md
> +Нас часто спрашивают: это нормально для джуниора, работать на удалёнке?
Предлагаю убрать это предложение, а сразу переходить к сути. Без него этот абзац не меняется по смыслу.

2018-02-25 19:55 UTC, artemiy312 commented on src/dev/junior_on_remote.md
> +1. совместная работа над задачами.
Над задачами можно работать не только в офисе, но и удаленно. Как пункт про "полезность офиса" воспринимается с натяжкой

2018-02-25 19:55 UTC, artemiy312 commented on src/dev/junior_on_remote.md
> +Всё равно будет полезно.
Не понял пойнт. Будет полезно общаться о чем угодно?

2018-02-25 19:55 UTC, artemiy312 commented on src/dev/junior_on_remote.md
> +- остальные 3ч в рабочий день ботаем качественные книги или лекции (не статьи на Хабре);
>(не статьи на Хабре);

я бы убрал это, а то вдруг кто-то хабр очень любит и не пойдет к нам из-за этого :)

2018-02-25 20:01 UTC, artemiy312 commented on src/dev/junior_on_remote.md
> +Вот чем полезен офис для вашего развития:
Возможно стоит назвать это так:
"Вот чем работа в офисе полезна для вас:"

Тогда получиться добавить сюда еще какие-то пункты (про печеньки), кроме живого общения :)
Или вовсе убрать это.

2018-02-25 20:28 UTC, artemiy312 commented
@duker33 
Я думаю, главная причиной желания джуниора работать в офисе является мысль о том, что его всему научат, направят в нужное русло, покажут лучший путь и тд. Самое сложно, когда ты джуниор без опыта это: расставлять приоритеты в учебе, определять, чему стоит уделять больше времени, а чему меньше, находить ошибки и недочеты в своей работе и главное - отличать хорошее от плохого.
Джуниор нуждается в критике и менторстве.

Мысль о работе удаленно, вызывает у джуниора дискомфорт, потому-что он не представляет процесс работы и не участвовал в больших проектах с кучей технологий и страшных слов. Он не знает, что половина проблем, с которыми он будет сталкиваться очень просто решать с помощью интернета (не только с помощью коллег из офиса, которые все подскажут) и здравого смысла.

2018-02-26 08:12 UTC, duker33 commented on src/dev/junior_on_remote.md
> +Второй пункт выглядит ожидаемо, а вот первый - нет. Как и их разделение.
@artemiy312 , традиционно считается, что важен сам контент, а не живые люди, которые его говорят.
А я тут взял и говорю, что смотреть на крутых живых людей - это также полезно, как и сам контент. Поэтому неожидаемо.

Но, раз у тебя возник вопрос, значит я выдал мысль неточно. Подумаю как это пофиксить.
Один из вариков - просто снесу домыслы про "ожидаемо/неожидаемо"

TODO

2018-02-26 08:16 UTC, duker33 commented on src/dev/junior_on_remote.md
> +Нас часто спрашивают: это нормально для джуниора, работать на удалёнке?
@artemiy312 , сначала нужно как-то обозначить что вообще происходит.
Самый простой и распространённый подход - описывают проблему. А вся дальнейшая статья - её углубление и решение.

Эта статья родилась ровно из этого вопроса. Написал я её только затем, чтобы не отвечать на этот же вопрос миллиард раз в чатах. А вопрос мне видится хорошим.
Не говорю, что это идеальное вступление, но какое-то должно быть.

2018-02-26 08:20 UTC, duker33 commented on src/dev/junior_on_remote.md
> +1. совместная работа над задачами.
@artemiy312 , видишь какая у меня тут линия:

- В голове у джунов засела мысль "я должен работать в офисе, чтобы прокачаться!" (вспоминаем нашего Диму))
- Мы задаём себе вопрос - чем офис помогает прокачаться?
- Находим эти два пункта
- Выясняем, что офис - не единственный способ претворить в жизнь эти два пункта. Есть и ещё

Я не говорю, что совместная работа над задачами возможна только в офисе. Я говорю, что в нём она возможна тоже.
Не знаю как кратко добавить эту мысль в предложение перед списком. Решил, что лучше никак =)
Если считаешь по-другому, предлагай

2018-02-26 08:21 UTC, duker33 commented on src/dev/junior_on_remote.md
> +Всё равно будет полезно.
да, это затравочка, ниже раскрываю мысль

2018-02-26 08:22 UTC, duker33 commented on src/dev/junior_on_remote.md
> +- остальные 3ч в рабочий день ботаем качественные книги или лекции (не статьи на Хабре);
TO-DO

2018-02-26 08:24 UTC, duker33 commented on src/dev/junior_on_remote.md
> +Вот чем полезен офис для вашего развития:
@artemiy312 , но тут мы говорим именно про развитие.

Конечная польза для читателя - только забустить своё развитие. Если офис помогает нам на этом пути - смотрим как ворваться в него. Если мешает - смотрим как убрать (мы выбрали второе).

Печеньки - это оффтоп, который ослабляет cohesion материала

2018-02-26 08:25 UTC, duker33 commented
@artemiy312 , да, твоя мысль выше - это +50% к материалу. Проработаю её

2018-03-15 06:44 UTC, duker33 commented
в pull#20 выставил новую версию статьи

2018-03-15 07:00 UTC, closed without merging