#19  "Dev with windows" article
fidals/fidals.com pull request #21
Opened 2018-03-19 07:25 UTC by duker33

Closes #19

2018-03-19 17:12 UTC, ArtemijRodionov requested changes

2018-03-19 17:12 UTC, ArtemijRodionov commented on src/dev/with_windows.md
> +Сегодня считаю этот метод самым простым и надёжным.
Предлагаю не разжигать holy war и опустим все комментарии касаемые качеств ОС: лучше/хуже и тд :) Задача статьи не искать несогласных, а помочь людям, которые работают под виндой

2018-03-20 05:54 UTC, duker33 commented on src/dev/with_windows.md
> +Сегодня считаю этот метод самым простым и надёжным.
@artemiy312 , я воспринимал это как вдохновение для новичков. Но ок, снесу

2018-03-20 14:08 UTC, ArtemijRodionov requested changes
Выпиливаем холиварные моменты

2018-03-20 14:08 UTC, artemiy312 commented on src/dev/with_windows.md
> +## Зачем под Виндой?
Этот пункт тоже стоит выпилить

2018-03-20 14:08 UTC, artemiy312 commented on src/dev/with_windows.md
> +Винда - лучшая на мой вкус ОС для повседневной работы.
Это предложение тоже

2018-03-21 05:46 UTC, duker33 commented on src/dev/with_windows.md
> +## Зачем под Виндой?
@artemiy312 , хм, я надеялся, что это избавит некоторых людей от страданий.
Они с самого начала будут находиться под давлением ~неоправданного~ переезда на Никс,
а в начале есть дела поважнее.

Но сам заголовок статьи и её наличие уже должен снять это давление, да

2018-03-21 20:26 UTC, artemiy312 commented on src/dev/with_windows.md
> +## Зачем под Виндой?
@duker33 Как раз таки, мы будем давить, если будем писать А лучше/хуже Б. Мне кажется, это не может быть объективной темой, поэтому лучше не развивать ее :)

2018-03-21 20:28 UTC, ArtemijRodionov approved these changes

2018-03-22 06:42 UTC, duker33 commented on src/dev/with_windows.md
> +## Зачем под Виндой?
@artemiy312 , "там где начинались Небо и Земля, не было имён" Лао Зцы.
Всё, что сказано словами, не может быть объективно. Мы же все люди.
Парни, которые этого не понимают, пройдут мимо нас. И нам же от этого лучше =)

2018-03-22 06:44 UTC, merged