#8  Test process article
fidals/fidals.com pull request #22
Opened 2018-03-21 06:39 UTC by duker33

Этот текст не стоит вытачивать по стилистике, я просто заменил им слова в разговоре по связи.
Но сам процесс стоит проверить

2018-03-21 20:14 UTC, ArtemijRodionov requested changes

2018-03-21 20:14 UTC, ArtemijRodionov commented on src/dev.md
> +1. Познакомимся голосом по связи. Это необязательно, но нам бы хотелось.
голосом -> устно

2018-03-21 20:14 UTC, ArtemijRodionov commented on src/dev/test_proccess.md
> +На этом этапе мы уже познакомились или голосом или через сообщения,
голосом -> устно

2018-03-21 20:14 UTC, ArtemijRodionov commented on src/dev/test_proccess.md
> +Мы работаем по стандартному [github flow](https://guides.github.com/introduction/flow/).
<img width="833" alt="default" src="https://user-images.githubusercontent.com/13870342/37710781-c07b3bd4-2d1f-11e8-8bd8-7d2abbd7896d.png">

По гит флоу, мы должны деплоить задачу перед ее мержем в мастер, но мы этим не занимаемся

2018-03-21 20:14 UTC, ArtemijRodionov commented on src/dev/test_proccess.md
> +Сделать задачу можно только одним способом - создать pull request с кодом, который её резолвит.
резолвит -> решает

2018-03-22 06:30 UTC, duker33 commented on src/dev.md
> +1. Познакомимся голосом по связи. Это необязательно, но нам бы хотелось.
@artemiy312 , думаю, "голосом" лучше вяжется со словом "связь".
Она же voice call = голосовая связь. Устойчивый термин, просто я его сделал не таким канцеляритным

2018-03-22 06:30 UTC, duker33 commented on src/dev/test_proccess.md
> +На этом этапе мы уже познакомились или голосом или через сообщения,
обсуждаем выше

2018-03-22 06:32 UTC, duker33 commented on src/dev/test_proccess.md
> +Мы работаем по стандартному [github flow](https://guides.github.com/introduction/flow/).
оке, скажу, что у нас этого нету

TODO

2018-03-22 06:32 UTC, duker33 commented on src/dev/test_proccess.md
> +Сделать задачу можно только одним способом - создать pull request с кодом, который её резолвит.
TODO

2018-03-22 06:32 UTC, duker33 commented
обсуждение по "голосом" vs "устно"

2018-03-22 14:06 UTC, artemiy312 commented on src/dev.md
> +1. Познакомимся голосом по связи. Это необязательно, но нам бы хотелось.
@duker33 

Голос - это звук, возникший благодаря воздуху проходящему, через голосовые связки, заставляя их вибрировать. Наверное получается, что если бы мы говорили голосом, то мы бы не использовали язык и губы для этого :)

Устно - произнесенное словами

Я бы написал так: "Познакомимся устно по связи (телеграмму, телефону)."
Можешь решать сам, это не принципиальный момент.

2018-03-22 14:07 UTC, ArtemijRodionov approved these changes
Ответил по поводу "устно vs голосом". Решать тебе

https://github.com/fidals/fidals.com/pull/22#discussion_r176431273

2018-03-23 07:09 UTC, duker33 commented on src/dev.md
> +1. Познакомимся голосом по связи. Это необязательно, но нам бы хотелось.
оставлю "голосом", это более понятно из-за развитого UX к этому слову. Понимаю, что "устно" звучит более строго, стройно и корректно.
Но в системе приоритетов текстов для инета понятность стоит куда выше корректности, выберу её

2018-03-23 07:10 UTC, merged